# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Temperature Plotting

# when and where this code will run (we do not want to run this for all branches)
# now we run this on every push and pull request to the main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build: # this does not have to be called build -> can have more descriptive name

    runs-on: ubuntu-latest # defines the operating system (can be windows or whatever else, also a combination with ne file is possible)

    steps: # each dash is one step 
    - uses: actions/checkout@v3 # clones my repo basically
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10" # quotes important
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        PYTHONPATH=. pytest
