# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Temperature Plotting

# when and where this code will run (we do not want to run this for all branches)
# now we run this on every push and pull request to the main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test: # this does not have to be called build or test -> can have more descriptive name
    strategy: # this is how we test multiple oses
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest] # we will run all combinations
        pt_version: ["3.9", "3.10"]
      fail-fast: false # always run all options -> do not cancel everything if one fails

#     runs-on: ubuntu-latest # defines the operating system (can be windows or whatever else, also a combination (see above)
    runs-on: ${{ matrix.os }} # names in matrix (like os here) are variables that we can use in the file to replace values

    steps: # each dash is one step 
    - uses: actions/checkout@v3 # clones my repo basically
    - name: Set up Python ${{ matrix.os }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.pt_version }} # quotes important in the list
    - name: Install dependencies
      shell: bash # fixes an issue when we run on windows
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      shell: bash
      run: |
        PYTHONPATH=. pytest
